project:
  type: website
  output-dir: docs

website:
  title: "Shaurya Chauhan - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Labs
        menu:
          - href: Labs/Lab0/lab0_template.qmd
            text: "Lab 0: dplyr Basics"

          - href: Labs/lab_1/lab1_template.qmd
            text: "Lab 1: Census Data Exploration"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto



