project:
  type: website
  output-dir: docs

website:
  title: "Shaurya Chauhan - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Labs
        menu:
          - href: labs/lab_0/
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/
            text: "Lab 1: Census Data Exploration"
          - href: labs/lab_2/
            text: "Lab 2: Spatial Analysis and Visualization"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

render:
  - index.qmd
  - labs/**/index.qmd




